steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && [['build', '-t', 'gcr.io/$PROJECT_ID/${BRANCH_NAME}/prod:$BUILD_ID', '.']]  && [['push', 'gcr.io/$PROJECT_ID/${BRANCH_NAME}/prod']] || exit 0

#scm build
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "scm-release" ]] && [['build', '-t', 'gcr.io/$PROJECT_ID/${BRANCH_NAME}/scm:$BUILD_ID', '.']] && [['push', 'gcr.io/$PROJECT_ID/${BRANCH_NAME}/scm']] || exit 0
