steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "master" ]] && docker build -t gcr.io/$PROJECT_ID/${_SERVICE_NAME}/prod:$BUILD_ID . && docker push gcr.io/$PROJECT_ID/${_SERVICE_NAME}/prod || exit 0

#scm build
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" == "scm*" ]] && docker build -t gcr.io/$PROJECT_ID/${_SERVICE_NAME}/scm:$BUILD_ID . && docker push gcr.io/$PROJECT_ID/${_SERVICE_NAME}/scm || exit 0
